package app

import (
	"os"
	"strings"
	"testing"
	"time"
)

func TestSaveReportWritesMarkdownUnderDataHome(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)

	now := time.Date(2026, 5, 30, 12, 34, 56, 0, time.UTC)
	path, err := saveReportAt("NVDA 지금 사도 될까?", "# Report\n\nBody", now)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(path, dir+"/gacha/reports/") {
		t.Fatalf("unexpected report path: %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	for _, expected := range []string{
		"# Report",
		"Generated by: gacha",
		"Original question: NVDA 지금 사도 될까?",
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("saved report did not contain %q", expected)
		}
	}
}

func TestSaveReportDoesNotOverwriteSameSecondAndQuery(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)
	now := time.Date(2026, 5, 30, 12, 34, 56, 0, time.UTC)

	first, err := saveReportAt("NVDA", "first report", now)
	if err != nil {
		t.Fatal(err)
	}
	second, err := saveReportAt("NVDA", "second report", now)
	if err != nil {
		t.Fatal(err)
	}
	if first == second {
		t.Fatalf("report paths collided: %s", first)
	}
	firstData, err := os.ReadFile(first)
	if err != nil {
		t.Fatal(err)
	}
	secondData, err := os.ReadFile(second)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(firstData), "first report") || !strings.Contains(string(secondData), "second report") {
		t.Fatalf("saved reports were not preserved: first=%q second=%q", firstData, secondData)
	}
}

func TestReportFileNameUsesReadableSlug(t *testing.T) {
	got := reportFileName(time.Date(2026, 5, 30, 12, 34, 56, 0, time.UTC), "NVDA 지금 사도 될까?")
	if got != "20260530-123456-nvda-지금-사도-될까.md" {
		t.Fatalf("unexpected file name: %s", got)
	}
}

func TestReportSaveAnswerParsing(t *testing.T) {
	for _, answer := range []string{"y", "yes", "Y", "예", "네"} {
		if !wantsSaveReport(answer) {
			t.Fatalf("expected %q to save", answer)
		}
	}
	for _, answer := range []string{"n", "no", "N", "아니요", "아니오"} {
		if !refusesSaveReport(answer) {
			t.Fatalf("expected %q to refuse save", answer)
		}
	}
	if wantsSaveReport("maybe") || refusesSaveReport("maybe") {
		t.Fatal("unexpected parse for ambiguous answer")
	}
}

func TestDetailedAnalysisAnswerParsing(t *testing.T) {
	for _, answer := range []string{"d", "detail", "details", "상세", "상세분석", "자세히", "더 자세히"} {
		if !wantsDetailedAnalysis(answer) {
			t.Fatalf("expected %q to request details", answer)
		}
	}
	if wantsDetailedAnalysis("new question") {
		t.Fatal("unexpected detail parse for ordinary text")
	}
}
